# @lg-sh on github

# ---- KITTY CONF ----

shell /usr/bin/fish
font_family      JetBrainsMono Nerd Font
font_size        13.0
disable_ligatures always


# ---- LOOK ----

background       #000000
foreground       #c5c8c6
cursor           #ffffff
cursor_shape     block
cursor_blink_interval 0

# Cor de seleção de texto 
selection_background #373b41
selection_foreground #ffffff

# ---- CUSTOM ----

map ctrl+equal    change_font_size all +2.0
map ctrl+minus    change_font_size all -2.0
map ctrl+c       copy_to_clipboard
map ctrl+v       paste_from_clipboard
map shift+insert paste_from_clipboard

enable_audio_bell no

