# @username on github

# ---- I3STATUS CONFIG ----

order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "ethernet _first_"
order += "path_exists VPN"
order += "tztime local"

# --------
cpu_temperature 0 {
        format = " CPU TEMP   %degrees °C "
        path = "/sys/class/hwmon/hwmon0/temp1_input"
}

memory {
        format = " RAM USED   %used "
}

disk "/" {
        format = " DISK AVAILABLE   %avail "
}

ethernet _first_ {
        format_up = " 󰈀  %ip "
        format_down = " 󰈀 %down "
}

path_exists VPN {
        format = " 󰒄 ProtonVPN: ON "
        format_down = " 󰒄 ProtonVPN: OFF "
        path = "/proc/sys/net/ipv4/conf/proton0" # Modifique de acordo com seu OS
}

tztime local {
        format = " 󱑍 %d/%m: %H:%M "
}
